---
title: "DATA607_Project 3 - Data Science Skills"
author: "David Simbandumwe"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
    extra_dependencies:
    - geometry
    - multicol
    - multirow
  html_document:
    df_print: paged
  rmdformats::robobook:
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(tidyverse)
library(knitr)
library(XML)
library(curl)
library(RCurl)
library(jsonlite)
library(dplyr)
library(openintro)
library(RMySQL)
library(ggplot2)

```



#

```{r}

usr <- keyring::key_list("DATA607")[1,2]
pwd <-  keyring::key_get("DATA607", usr)
con = dbConnect(MySQL(), user=usr, password=pwd, dbname='DATA607', host='localhost')

```



```{r read create database tables}

# Job Opening
query <- "DROP TABLE IF EXISTS JobOpenings CASCADE;"
results <- dbSendQuery(con, query)
query<-"CREATE TABLE JobOpenings (
    job_id			    INT,
    min_experience		INT,
    max_experience		INT,
    skill			    TEXT,
    location		    TEXT,
    min_salary		    INT,
    max_salary		    INT,
    company_id		    INT,
    PRIMARY KEY (job_id)
);"
results <- dbSendQuery(con, query)
dbClearResult(results)



query <- "DROP TABLE IF EXISTS JobSeekers CASCADE;"
results <- dbSendQuery(con, query)
query <- "CREATE TABLE JobSeekers (
    resp_id		        INT,
    gender		        TEXT,
    age		            INT,
    location	        TEXT,
    education	        TEXT,
    major	            TEXT,
    title	            TEXT,
    industry	        TEXT,
    experience	        TEXT,
    dataScientist	    TEXT,
    primarySkill	    TEXT,
    skill		        TEXT,
    PRIMARY KEY (resp_id)
);"
results <- dbSendQuery(con, query)
dbClearResult(results)



query <- "DROP TABLE IF EXISTS JobSalary CASCADE;"
results <- dbSendQuery(con, query)
query <- "CREATE TABLE JobSalary	 (
    id			        INT,
    min			        INT,
    max			        INT,
    PRIMARY KEY (id)
);"
results <- dbSendQuery(con, query)
dbClearResult(results)



query <- "DROP TABLE IF EXISTS JobLocation CASCADE;"
results <- dbSendQuery(con, query)
query <- "CREATE TABLE JobLocation	 (
    id				INT,    
    location_id		INT
);"
results <- dbSendQuery(con, query)
dbClearResult(results)



query <- "DROP TABLE IF EXISTS JobRequirements CASCADE;"
results <- dbSendQuery(con, query)
query <- "CREATE TABLE JobRequirements (
    id			    INT,
    skill_id		INT
);"
results <- dbSendQuery(con, query)
dbClearResult(results)



query <- "DROP TABLE IF EXISTS JobSeekerSkills CASCADE;"
results <- dbSendQuery(con, query)
query <- "CREATE TABLE JobSeekerSkills (
    id			    INT,
    skill_id		INT,
    PRIMARY KEY (id)
);"
results <- dbSendQuery(con, query)
dbClearResult(results)



query <- "DROP TABLE IF EXISTS JobSeeker CASCADE;"
results <- dbSendQuery(con, query)
query <- "CREATE TABLE JobSeeker (
    id			        INT,  
    location		    TEXT,
    education_level_id	INT,
    major_id		    INT,
    title_id		    INT,
    industry_id		    INT,
     PRIMARY KEY (id)
);
"
results <- dbSendQuery(con, query)
dbClearResult(results)




dbDisconnect(con)


```


# Read data
```{r}

rm(list=ls())

skills_df <- read_csv( file = "https://raw.githubusercontent.com/dsimband/DATA607Team3/master/csv/Final_Train_Dataset.csv")
names(skills_df)[1] <- "id"


tmp <- skills_df %>%
    select(id, key_skills) %>%
    separate_rows(
        key_skills,
        convert = TRUE,
        sep = "\\,"
    )
    

tmp <- tmp %>% 
    mutate(
        key_skills = str_to_lower(key_skills),
        key_skills = str_replace_all(key_skills, "\\.{3}", "" ),
        key_skills = str_trim(key_skills)
    )


ds_skills_df <- tibble ( key_skills = c("sql", "r" , "data science", "python", "matlab", "machine learning"))



tmp <- tmp %>% filter(key_skills %in% ds_skills_df$key_skills) %>% arrange(id)


    

id_df <- tmp %>%
    select(id) %>%
    distinct()


tmp <- skills_df %>% 
    inner_join( id_df,by="id" ) %>%
    right_join(tmp, by="id") %>%
    mutate (
        flag = TRUE
    )




tmp <- tmp %>% 
    spread(key_skills.y, flag, convert=TRUE, fill=FALSE) 
    


```














# Introduction





# HTML



# XML



# Conclusions













